// <auto-generated />
using FutureOfWorkAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutureOfWorkAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115021900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("FutureOfWorkAPI.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("FutureOfWorkAPI.Models.Profissional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaInteresse")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEmpregado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NivelHabilidade")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("FutureOfWorkAPI.Models.ProfissionalCurso", b =>
                {
                    b.Property<int>("ProfissionalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfissionalId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("ProfissionalCurso");
                });

            modelBuilder.Entity("FutureOfWorkAPI.Models.ProfissionalCurso", b =>
                {
                    b.HasOne("FutureOfWorkAPI.Models.Curso", "Curso")
                        .WithMany("Profissionais")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutureOfWorkAPI.Models.Profissional", "Profissional")
                        .WithMany("Cursos")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("FutureOfWorkAPI.Models.Curso", b =>
                {
                    b.Navigation("Profissionais");
                });

            modelBuilder.Entity("FutureOfWorkAPI.Models.Profissional", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
